### ISSUE TITLE
Invalid git clone (edit: on windows machines)

### ISSUE THREAD

**Issue by gcasale** [mmagnus/pubmex#8]
The colon in 'demo/10.1261:rna.418407.pdf' causes problems in cloning from windows machines.
---
Cloning into 'pubmex'...
remote: Enumerating objects: 426, done.
remote: Counting objects: 100% (9/9), done.
remote: Total 426 (delta 8), reused 8 (delta 8), pack-reused 417 eceiving obj
Receiving objects: 100% (426/426), 3.79 MiB | 2.86 MiB/s, done.
Resolving deltas: 100% (252/252), done.
error: invalid path 'demo/10.1261:rna.418407.pdf'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by mmagnus** [comment]
Eh, works for me ;-) I guess the problem is ':' in the file name here. 
Anyway @gcasale I'm afraid that the script will not work on Windows, at least it's not been tested by me.

``` 
# on my mac
git clone https://github.com/mmagnus/pubmex.git
Cloning into 'pubmex'...
remote: Enumerating objects: 426, done.
remote: Counting objects: 100% (9/9), done.
remote: Total 426 (delta 8), reused 8 (delta 8), pack-reused 417
Receiving objects: 100% (426/426), 3.79 MiB | 1.85 MiB/s, done.
Resolving deltas: 100% (252/252), done.
```
